### ISSUE TITLE
Strange behaviour on collision for objects moving from right to left

### ISSUE THREAD

**Issue by prat-man** [dyn4j/dyn4j#62] opened 2019-08-30 22:55 UTC
After building the latest code (from upcoming release 3.3.1), I observed a strange behavior.

For any object moving from _**right to left**_ hitting another object of infinite mass, it is displaying erratic behavior as can be seen in the following GIF.

Behavior when executed in version 3.3.1
![ezgif com-crop](https://user-images.githubusercontent.com/13336387/64054211-9ca9eb00-cba3-11e9-899f-2c21127bec8b.gif)

To compare, I have executed the same code in version 3.3.0
![ezgif com-crop (2)](https://user-images.githubusercontent.com/13336387/64054816-6de14400-cba6-11e9-8806-d1cf0fad0487.gif)

Here the moving object is a rectangular fixture and the fixed object is a set of links.
Strangely, this behavior can only be reproduced if the object is moving from right to left.

It seems like a regression to me.
Can you please check if it is a bug or am I missing something?

**Comment by wnbittle** [comment] 2019-08-31 03:19
Thanks again for the report.  It's a regression in the SequentialImpulses.solvePositionContraints method.  I have committed a fix for this.  Can you try with latest from source?

**Comment by prat-man** [comment] 2019-08-31 07:01
I have compiled the latest code. It is working perfectly now. Both the collision and the raycast. Thanks.

![ezgif com-crop](https://user-images.githubusercontent.com/13336387/64060499-13b6a200-cbeb-11e9-822d-809802570bed.gif)

**Comment by wnbittle** [comment] 2019-08-31 17:54
Awesome!  I'm going to go ahead and close this issue since it's a regression for unreleased code.

**Closed by wnbittle** 2019-08-31 17:54 UTC
Labels: bug
