### ISSUE TITLE
RevoluteJoint Angle Limits Not Working Properly

### ISSUE THREAD

**Issue by DyloniusMonk** [dyn4j/dyn4j#89] opened 2019-11-13 18:51 UTC
When RevoluteJoint angle limits are near -pi/pi, when the joint passes a limit, the 'joint angle' can flip (e.g. from -pi to pi), which can cause the limit to have no effect.  Attached the RevoluteJoint class (3.3.0) with minor changes made and successfully tested to address this issue.  See the class comment for more information.
[RevoluteJointCustom.txt](https://github.com/dyn4j/dyn4j/files/3842956/RevoluteJointCustom.txt)

**Comment by wnbittle** [comment] 2019-11-16 05:31
A couple of questions:
1. Did using the setReferenceAngle(double) method not work in your case?  See the class javadoc for RevoluteJoint.
1. From what I'm seeing the replacement of the LimitState.EQUAL with a boolean was so that you could use the closer limit during position constraint solving.  Can you confirm?
1. Shouldn't you reset the treatLimitsAsEqual flag to false in the initializeVelocityConstraints method before checking whether they're equal again?

I like the modification because the reference angle becomes less useful and the joint is easier to work with.

**Comment by wnbittle** [comment] 2019-11-23 01:22
I got around to trying this modification, but I'm finding it really unstable - somewhere in the position constraint solver.  I'm closing as it works for you and dyn4j already has a solution for this issue: setReferenceAngle(double) that's clearly defined in the class level javadocs.

**Closed by wnbittle** 2019-11-23 01:22 UTC
Labels: enhancement

**Comment by DyloniusMonk** [comment] 2019-11-23 21:14
Hi William,

Sorry, I replied to your questions via email, but it looks like my email client didn't use the reply-to address correctly, so I don't think the email went through.  I'll include it below for reference.  Thanks for looking into this issue - just wanted to bring it to your attention.

-Dylan


On 11/16/2019 5:14 PM, Dylan Jacobs wrote:

Hi William,

First, thank you so much for all of your hard work on dyn4j.  I'm developing a Java-based platform for evolutionary machine learning, and I'm using dyn4j to support 2D physical simulations.  I've been working on the platform for almost 7 years now, and it should be ready for an initial release soon.

See below for my responses to your questions.

Happy to discuss this further!

-Dylan


1) Did using the setReferenceAngle(double) method not work in your case? See the class javadoc for RevoluteJoint.

[DJ] In my use-case, I want to make it as easy as possible for the user to build a robot body, and defining joint limits in terms of body2 rotation w.r.t. body1 (instead of w.r.t. reference angle) is more intuitive.  So reference angle is always set to 0 in my use-case.  Even if it wasn't, I think that the same problem would still occur.  getRelativeRotation() returns an angle on [-pi, pi], so there must be a point where the method is returning, for example, -pi, and then body1's rotation changes very slightly, and now the method is returning a number just less than pi.  This is the 'jump' that this fix is trying to address.  In a scenario where you have a motor applying torque in a direction, if one of your limits is near -pi or pi, if the Body is rotating fast enough, as you know, the Body will pass the limit, and then impulse is applied in the opposite direction to bring it back to the limit.  But if the relative angle also 'flips' during this step, the impulse will be applied in the wrong direction (the same direction that the Body is rotating), and the motor will just keep spinning the body.  I also wanted to ensure that limits could be on [-pi, pi], instead of the current (-pi, pi) that is documented.

2) From what I'm seeing the replacement of the LimitState.EQUAL with a boolean was so that you could use the closer limit during position constraint solving. Can you confirm?

[DJ] This solution is pretty suboptimal, and it's not good to use this boolean and just not use LimitState.EQUAL.  The reason I'm doing this is so that in initializeConstraints(), we do some calculations to see if we are in the AT_LOWER or AT_UPPER state (could rename AT_OR_PAST_LOWER and AT_OR_PAST_UPPER for clarity), and if so save the new state, but it's also possible that we can be in the equivalent of the EQUAL state at the same time.  Then, solveVelocityConstraints() needs to know whether we are in the equivalent of the EQUAL state, and both solveVelocityConstraints() and solvePositionConstraints() need to now whether we are in AT_LOWER or AT_UPPER.  It would probably be ideal to remove LimitState.EQUAL from the enum, use something like the treatLimitsAsEqual boolean instead.

3) Shouldn't you reset the treatLimitsAsEqual flag to false in the initializeVelocityConstraints method before checking whether they're equal again?

[DJ] Yes, good catch.  Just need to add an else branch that sets to false.

Miscellaneous: I notice that the corresponding Box2D class does everything in terms of body2 w.r.t body1 (which I find to be the most intuitive), whereas the dyn4j class is the other way around.  Do you remember if there was a specific reason for this?  I started trying to go through and reverse everything in the logic, but then I decided to just keep my change as simple as possible to minimize risk.  I found that if you just reverse the sign and order of the limits when you set them, this allows you to define limits as body2 rotation w.r.t body1.

**Comment by wnbittle** [comment] 2019-12-07 03:20
Makes sense.  Did you see stability issues in your tests?  What I would see is that when it got to the limit it would bounce away from it rather than sit on the limit.

Regarding the limit definitions wrt. body 1 or 2 - simple answer: I derived the constraints myself and stuck with that derivation.

**Comment by DyloniusMonk** [comment] 2019-12-29 14:47
Yes, I did see some stability issues in my testing.  I've attached an improved solution below.  This solution properly fixes the issue with joint angle limits near -pi/pi, and significantly reduces the 'high-frequency jerking' observed when at/near a limit.  I would ideally like to be able to further reduce or eliminate this jerking (possibly by introducing some soft resistance as a limit is approached to counteract the motor), but for my use-case this solution is good enough for now.  Maybe we could work together to try to figure out how to do this?  

Summary of changes made:

1. initializeConstraints(...)
- Assume joint angle could have passed a joint angle limit, passed -pi/pi and 'flipped' during the current step.  Let the closest joint angle limit dictate whether in the AT_LOWER or AT_UPPER state.  Otherwise, if joint angle flipped, the limit will have no effect, and the joint will continue to rotate.
- Code cleanup to make limit state semantics more clear

2. solveVelocityConstraints(...)
- Added else branches that were missing in dyn4j code but present in Box2D code.  This was observed to significantly improve stability at/near joint angle limits.

3. solvePositionConstraints(...)
- If joint angle passed a joint angle limit, passed -pi/pi and flipped during the current step, j may not be on [-pi, pi].  Ensure j is on [-pi, pi], using same approach as getRelativeRotation().  This ensures that j has the intended value.  Otherwise, if joint angle flipped, limit may have no effect, or instability may be observed at/near limit.
- Code cleanup, make more intuitive and easier to understand.  Provide examples in a code comment that explain the angular correction approach.
- Factor out code that ensures joint angle on [-pi, pi] into a helper method, use this method in all places where this logic is needed to prevent code duplication


[RevoluteJointCustom.txt](https://github.com/dyn4j/dyn4j/files/4008141/RevoluteJointCustom.txt)

**Comment by wnbittle** [comment] 2019-12-31 17:39
Thanks for sticking with it.  
[test-new-revolute.zip](https://github.com/dyn4j/dyn4j/files/4013199/test-new-revolute.zip)

This looks a lot better, but I'm still having issues with setting the limits.  

Problem 1:
It seems to be treating the upper half of the unit circle as [-180, 0] instead of [180, 0].  So setting the limits to [-30, 170] puts it at 30 degrees above the positive x-axis and 10 degrees below the negative x-axis.

Problem 2:
It seems i can't set the upper limit to more than 180.  The original documentation has this constraint (not enforced), but you would use the reference angle to fix this.  My understanding of this change was to remove the need of the reference angle.  For example, setting the limits to [-90, 240] behaves like [-90, 180].  I can get [-90, 240] to work by setting the reference angle to 90 degrees.

Problem 3:
I'm still seeing jumping between the limits.  In the [-90, 240] case above, if I apply enough force, it'll wrap around just like the current implementation.  This is a similar issue to collision tunneling.  I don't think this is what you are trying to fix, but I wanted to call it out just in case it was.

Do you have a reproduction case of the original issue?  I get the feeling that I don't fully understand the problem you are trying to solve.  I've attached the code I'm using to test for reference.
